AllCops:
  TargetRubyVersion: 2.7.0
  Exclude:
    - "bin/*"
# Commonly used screens these days easily fit more than 80 characters.
Layout/LineLength:
  Max: 120
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/Documentation:
  Enabled: false
